export const products = [
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C640',
  //   makat: '81UE001GUS',
  //   image: 'images/C640-81UE001GUS.jpg',
  //   category: 'Computers',
  //   price: '3490',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'i7-10510',
  //     hardDiskSize: '512',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 13 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TC000JUS',
  //   image: 'images/C740-81TC000JUS.jpg',
  //   category: 'Computers',
  //   price: '3510',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'i5-10210U',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TD0005US',
  //   image: 'images/C740-81TD0005US.jpg',
  //   category: 'Computers',
  //   price: '4470',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'i7-1051',
  //     hardDiskSize: '512',
  //     computerMemorySize: '12',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TD0006US',
  //   image: 'images/C740-81TD0006US.jpg',
  //   category: 'Computers',
  //   price: '3150',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'i5-10210',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO ULTRA THIN',
  //   brand: 'LENOVO',
  //   model: 'EVOO',
  //   makat: 'EVC156',
  //   image: 'images/EVOO-EVC156.jpg',
  //   category: 'Computers',
  //   price: '2090',
  //   countInStock: 4,
  //   isNewComputer: 'no',
  //   detail: {
  //     CPUmodel: 'i7-6660',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: '15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO 14IIL05',
  //   brand: 'LENOVO',
  //   model: 'FLEX',
  //   makat: '81X10009US',
  //   image: 'images/FLEX-81X10009US.jpg',
  //   category: 'Computers',
  //   price: '3110',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'i5-1035',
  //     hardDiskSize: '512',
  //     computerMemorySize: '16',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO 2IN1',
  //   brand: 'LENOVO',
  //   model: 'FLEX5',
  //   makat: '81X2000HUS',
  //   image: 'images/FLEX5-81X2000HUS.jpg',
  //   category: 'Computers',
  //   price: '2385',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   detail: {
  //     CPUmodel: 'RYZEN-4300',
  //     hardDiskSize: '128',
  //     computerMemorySize: '4',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
];

export const users = [
  // {
  //   name: 'Oshri',
  //   email: 'admin@example.com',
  //   password: bcrypt.hashSync('1234', 8),
  //   isAdmin: true,
  // },
  // {
  //   name: 'Nati',
  //   email: 'user@example.com',
  //   password: bcrypt.hashSync('1234', 8),
  //   isAdmin: false,
  // },
];
