export const products = [
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C640',
  //   makat: '81UE001GUS',
  //   image: 'images/C640-81UE001GUS.jpg',
  //   category: 'Computers',
  //   price: '3490',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i7-10510',
  //     hardDiskSize: '512',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 13 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TC000JUS',
  //   image: 'images/C740-81TC000JUS.jpg',
  //   category: 'Computers',
  //   price: '3510',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-10210U',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TD0005US',
  //   image: 'images/C740-81TD0005US.jpg',
  //   category: 'Computers',
  //   price: '4470',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i7-1051',
  //     hardDiskSize: '512',
  //     computerMemorySize: '12',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA',
  //   brand: 'LENOVO',
  //   model: 'C740',
  //   makat: '81TD0006US',
  //   image: 'images/C740-81TD0006US.jpg',
  //   category: 'Computers',
  //   price: '3150',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-10210',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'EVOO ULTRA THIN',
  //   brand: 'EVOO',
  //   model: 'EVOO',
  //   makat: 'EVC156',
  //   image: 'images/EVOO-EVC156.jpg',
  //   category: 'Computers',
  //   price: '2090',
  //   countInStock: 4,
  //   isNewComputer: 'no',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i7-6660',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: '15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO 14IIL05',
  //   brand: 'LENOVO',
  //   model: 'FLEX',
  //   makat: '81X10009US',
  //   image: 'images/FLEX-81X10009US.jpg',
  //   category: 'Computers',
  //   price: '3110',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-1035',
  //     hardDiskSize: '512',
  //     computerMemorySize: '16',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO 2IN1',
  //   brand: 'LENOVO',
  //   model: 'FLEX5',
  //   makat: '81X2000HUS',
  //   image: 'images/FLEX5-81X2000HUS.jpg',
  //   category: 'Computers',
  //   price: '2385',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'AMD-4300',
  //     hardDiskSize: '128',
  //     computerMemorySize: '4',
  //     screen: 'מגע, מתהפך, 14 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO 15IIL05 2IN1',
  //   brand: 'LENOVO',
  //   model: 'FLX15',
  //   makat: '81X3000VUS',
  //   image: 'images/FLX15-81X3000VUS.jpg',
  //   category: 'Computers',
  //   price: '3580',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i7-1065',
  //     hardDiskSize: '512',
  //     computerMemorySize: '16',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'Dell Latitude 5470',
  //   brand: 'Dell',
  //   model: 'LAT',
  //   makat: '5470-256G',
  //   image: 'images/LAT-5470-256G.jpg',
  //   category: 'Computers',
  //   price: '2120',
  //   countInStock: 4,
  //   isNewComputer: 'no',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-6300',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: '14 אינץ',
  //     operatingSystem: 'Windows 10 Pro',
  //   },
  // },
  // {
  //   name: 'LENOVO GTX1650',
  //   brand: 'LENOVO',
  //   model: 'SLIM',
  //   makat: '82AE0003US',
  //   image: 'images/SLIM-82AE0003US.jpg',
  //   category: 'Computers',
  //   price: '4850',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i7-10750',
  //     hardDiskSize: '1024',
  //     computerMemorySize: '16',
  //     screen: '15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO ThinKPad',
  //   brand: 'LENOVO',
  //   model: 'X1-YOGA',
  //   makat: '20LES0CV00',
  //   image: 'images/X1-YOGA-20LES0CV00.jpg',
  //   category: 'Computers',
  //   price: '3840',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-8350',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מסך מגע, 14 אינץ, רזולציה 2קיי',
  //     operatingSystem: 'Windows 10 Pro',
  //   },
  // },
  // {
  //   name: 'LENOVO ThinkPad',
  //   brand: 'LENOVO',
  //   model: 'YOGA',
  //   makat: '20R5A000US',
  //   image: 'images/YOGA-20R5A000US.jpg',
  //   category: 'Computers',
  //   price: '3840',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-10210',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, 13 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO YOGA7',
  //   brand: 'LENOVO',
  //   model: 'YOGA',
  //   makat: '82BJ0001US',
  //   image: 'images/YOGA-82BJ0001US.jpg',
  //   category: 'Computers',
  //   price: '3630',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'i5-1135',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 15 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'LENOVO RYZEN',
  //   brand: 'LENOVO',
  //   model: 'YOGA',
  //   makat: '82FN003TUS',
  //   image: 'images/YOGA-82FN003TUS.jpg',
  //   category: 'Computers',
  //   price: '3420',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'no',
  //   detail: {
  //     CPUmodel: 'AMD-4650',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: 'מגע, מתהפך, 13 אינץ',
  //     operatingSystem: 'Windows 10 Home',
  //   },
  // },
  // {
  //   name: 'Asus VivoBook',
  //   brand: 'Asus',
  //   model: 'VivoBook',
  //   makat: 'X415JA-EK024',
  //   image: 'images/X415JA-EK024.jpg',
  //   category: 'Computers',
  //   price: '2190',
  //   countInStock: 4,
  //   isNewComputer: 'yes',
  //   officialImporter: 'yes',
  //   detail: {
  //     CPUmodel: 'i5-1035G1',
  //     hardDiskSize: '256',
  //     computerMemorySize: '8',
  //     screen: '14 אינץ',
  //     operatingSystem: 'none',
  //   },
  // },
];

export const benefits = [
  // {
  //   name: 'Windows 10 Pro 64bit',
  //   brand: 'Microsoft',
  //   makat: '1',
  //   image: 'images/benefits/win10-pro.jpg',
  //   category: 'Benefits',
  //   price: '600',
  //   countInStock: 1,
  //   description: 'מערכת הפעלה וונדוס פרו במחיר מוזל בקניית מחשב',
  // },
  // {
  //   name: 'Windows 10 Home 64bit',
  //   brand: 'Microsoft',
  //   makat: '2',
  //   image: 'images/benefits/win10-home.jpg',
  //   category: 'Benefits',
  //   price: '480',
  //   countInStock: 1,
  //   description: 'מערכת הפעלה ווינדוס הום במחיר מוזל בקניית מחשב',
  // },
  // {
  //   name: 'Anti Virus G-DATA',
  //   brand: 'G-DATA',
  //   makat: '3',
  //   image: 'images/benefits/antivirus-gdata.jpg',
  //   category: 'Benefits',
  //   price: '99',
  //   countInStock: 1,
  //   description: 'אנטי וירוס עם רישיון לשנה אחת',
  // },
  // {
  //   name: 'Anti Virus NOD32',
  //   brand: 'NOD32',
  //   makat: '4',
  //   image: 'images/benefits/antivirus-node32.jpg',
  //   category: 'Benefits',
  //   price: '129',
  //   countInStock: 1,
  //   description: 'אנטי וירוס עם רישיון לשנה אחת',
  // },
  // {
  //   name: 'Office Home&Business 2019',
  //   brand: 'Microsoft',
  //   makat: '5',
  //   image: 'images/benefits/office-home-business.jpg',
  //   category: 'Benefits',
  //   price: '999',
  //   countInStock: 1,
  //   description: 'מיקרוסופט אופיס גרסת ביסנס',
  // },
  // {
  //   name: 'Office Home&Student 2019',
  //   brand: 'Microsoft',
  //   makat: '6',
  //   image: 'images/benefits/office-home-student.jpg',
  //   category: 'Benefits',
  //   price: '719',
  //   countInStock: 1,
  //   description: 'מיקרוספט אופיס גרסת סטודנט',
  // },
  // {
  //   name: 'סט עכבר ומקלדת Lenovo 510',
  //   brand: 'Lenovo',
  //   makat: '7',
  //   image: 'images/benefits/keyboard-mouse-lenovo.jpg',
  //   category: 'Benefits',
  //   price: '115',
  //   countInStock: 4,
  //   description: 'עכבר מוזל למחשב',
  // },
  // {
  //   name: 'עכבר אלחוטי שחור Lenovo 310',
  //   brand: 'Lenovo',
  //   makat: '8',
  //   image: 'images/benefits/mouse-lenovo310.jpg',
  //   category: 'Benefits',
  //   price: '60',
  //   countInStock: 4,
  //   description: 'עכבר של לנובו מוזל',
  // },
  // {
  //   name: 'תיק צד למחשב',
  //   brand: 'Gold Touch',
  //   makat: '9',
  //   image: 'images/benefits/backpack-zad.jpg',
  //   category: 'Benefits',
  //   price: '40',
  //   countInStock: 4,
  //   description: 'תיק צד למחשב 15.6 יצרן Gold Touch',
  // },
  // {
  //   name: 'תיק גב למחשב',
  //   brand: 'Gold Touch',
  //   makat: '10',
  //   image: 'images/benefits/backpack-gav.jpg',
  //   category: 'Benefits',
  //   price: '129',
  //   countInStock: 4,
  //   description: 'תיק גב למחשב 15.6 יצרן Gold Touch',
  // },
];

export const users = [
  // {
  //   name: 'Oshri',
  //   email: 'admin@example.com',
  //   password: bcrypt.hashSync('1234', 8),
  //   isAdmin: true,
  // },
  // {
  //   name: 'Nati',
  //   email: 'user@example.com',
  //   password: bcrypt.hashSync('1234', 8),
  //   isAdmin: false,
  // },
];
