import bcrypt from 'bcryptjs';

export const products = [
  {
    name: 'LENOVO YOGA',
    brand: 'LENOVO',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '4450',
    countInStock: 3,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'HP laptop',
    brand: 'HP',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '4000',
    countInStock: 7,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'LG new laptop',
    brand: 'LG',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '1950',
    countInStock: 2,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'Samsung pro',
    brand: 'Samsung',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '2750',
    countInStock: 4,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'Lenovo pro',
    brand: 'Lenovo',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '11000',
    countInStock: 3,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'Toshiba pro',
    brand: 'Toshiba',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '2100',
    countInStock: 3,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    name: 'Apple pro',
    brand: 'Apple',
    model: 'C640',
    makat: '1',
    image: 'images/cmp1.jpg',
    category: 'Computers',
    price: '8100',
    countInStock: 3,
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
];

export const users = [
  {
    name: 'Oshri',
    email: 'admin@example.com',
    password: bcrypt.hashSync('1234', 8),
    isAdmin: true,
  },
  {
    name: 'Nati',
    email: 'user@example.com',
    password: bcrypt.hashSync('1234', 8),
    isAdmin: false,
  },
];
